There is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

**Reading Data From CSV**

In [3]:
df=pd.read_csv("hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

**Examining Missing Data if ANY**


In [5]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

**Check for percentage of Missing Data**

In [6]:
df.isnull().sum()/len(df)

experience                    0.250
test_score(out of 10)         0.125
interview_score(out of 10)    0.000
salary($)                     0.000
dtype: float64

**Drop columns with more than 25% of missing data**

df.drop('column_name',inplace=True,axis=1)

**Impute Substitute Values**
(Mean, Median or Mode)

**Impute Mean**
experience_mean = df['columnname'].mean()

experience_mean

df['columnname'].fillna(experiance_mean,inplace=True)

**Impute Median**

experience_median = df['columnname'].median()

experience_median

df['columnname'].fillna(experiance_median,inplace=True)

**Impute Mode**

df['columnname'].value_counts()

experience_mode = df['columnname'].value_counts().index[0]

experience_mode

df['columnname'].fillna(experiance_mode,inplace=True)


**Here in our situation we are imputing Mode for column experience**

In [7]:
df['experience'].value_counts()

two       1
five      1
ten       1
seven     1
three     1
eleven    1
Name: experience, dtype: int64

In [9]:
experience_mode = df['experience'].value_counts().index[0]
experience_mode

'two'

In [10]:
df['experience'].fillna(experiance_mode,inplace=True)

**Check for missing data**

In [11]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

**Now we will impute Median for column test_score(out of 10)**

In [15]:
test_score_median = df["test_score(out of 10)"].median()
test_score_median

8.0

In [16]:
df["test_score(out of 10)"].fillna(test_score_median,inplace=True)

**Check for missing data again**

In [17]:
df.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [22]:
df = df.rename(columns={"salary($)": 'salary'})

In [23]:
df.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary                        0
dtype: int64

In [29]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           2                    8.0                           9   50000
1           2                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    8.0                           7   72000
7          11                    7.0                           8   80000

**CREATE LINEAR REGRESSION MODEL**

In [30]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience',"test_score(out of 10)","interview_score(out of 10)"]],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Coefficients m1,m2,m3**

In [31]:
reg.coef_

array([3230.12552301, 1916.31799163, 2769.87447699])

**For intercept b**

In [32]:
reg.intercept_

9138.075313807567

**For Prediction**

In [33]:
reg.predict([[2,9,6]])

array([49464.43514644])

In [34]:
reg.predict([[12,10,10]])

array([94761.50627615])